# docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    container_name: currency-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src  # Hot reload 
      - ./data:/app/data  # SQLite database
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload