# docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    container_name: currency-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  redis:
    image: "redis:7-alpine"
    container_name: currency-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning